import { AdminSidebar } from "@/app/components/AdminSidebar/AdminSidebar";
import CursorEffect from "@/app/components/CursorEffect/CursorEffect";
import { cn } from "@/lib/utils";
import '../../global.css'
import DarkModeToggle from "@/app/components/DarkMode/DarkMode";

export const metadata = {
  title: "Israr Ahmad",
  description: "Generated by Next.js",
};


function AdminLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="/israr7.png"></link>
      </head>
      <body className="">
        <div
          className={cn(
            "w-full flex flex-1 flex-col md:flex-row border border-violet-500/20",
            "h-screen"
          )}
        >
          <AdminSidebar />
          {/* Content */}
          <main className="z-100 flex-1 p-6 overflow-y-auto">
            {children}
          </main>
        </div>
        <DarkModeToggle />
        <CursorEffect />
      </body>
    </html >
  );
}

export default AdminLayout;
