import { Toaster } from "react-hot-toast";
import "./global.css";

export const metadata = {
  title: "Israr Ahmad",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="/israr7.png" />
      </head>
      <body>
        <Toaster position="top-right" />
        {children}
      </body>
    </html>
  );
}
