import CursorEffect from './components/CursorEffect/CursorEffect';
import DarkModeToggle from './components/DarkMode/DarkMode';
import Footer from './components/Footer/Footer';
import Sidebar from './components/Sidebar/Sidebar';
import './global.css'

export const metadata = {
  title: "Israr Ahmad",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="/israr7.png"></link>
      </head>
      <body className="">
        <div id="root" className='relative w-full min-h-screen grid grid-cols-[350px_1fr] max-w-[1920px] mx-auto'>
          <Sidebar />
          <main className='w-full h-screen relative z-40 overflow-y-auto'>
            <DarkModeToggle />
            {children}
            <Footer/>
          </main>
        </div>
        {/* <CursorEffect /> */}
      </body>
    </html>
  );
}
