import CursorEffect from './components/CursorEffect/CursorEffect';
import DarkModeToggle from './components/DarkMode/DarkMode';
import Sidebar from './components/Sidebar/Sidebar';
import './global.css'

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <div id="root" className='relative w-full h-screen grid grid-cols-[350px_1fr] max-w-[1920px] mx-auto'>
          <Sidebar />
          <main className='w-full h-full relative z-40'>
            <DarkModeToggle />
            {children}
          </main>

          <CursorEffect />
        </div>
      </body>
    </html>
  );
}
